### ISSUE TITLE
Slack notification does not display the event's latest payload

### ISSUE THREAD

**Issue by jfragoulis** [getsentry/sentry#11002]
## Important Details

How are you running Sentry?

* [x] On-Premise docker
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

We have a channel in slack for errors of a certain type. These errors happen regularly but with a different payload each time. Sentry correctly packs them together and sends a notification to the designated slack channel. The problem is that the payload shown in slack is not correct, it is not the latest failure's.

### What you expected to happen

Display the payload of the latest failure.

**Comment by EvanPurkhiser** [comment]
Are you using the newest slack integration, or the older slack plugins?

**Comment by alexandrinaw** [comment]
We're using the newest slack integration and this happens to us too -- we have some errors that have slightly different text (for example `<Option X> not a valid choice for whatever`), that are thrown from the same place in our codebase & have the same stacktrace. They're being grouped together correctly, but the text that shows up in the slack notification is usually the wrong `Option Y`, from one of the previous instances of this event showing up.

**Comment by jfragoulis** [comment]
> Are you using the newest slack integration

Yes

**Comment by markstory** [comment]
Fixed in #12881

**Comment by ArcticSnowman** [comment]
This issue may not be fully resolved by #12881

**Comment by BYK** [comment]
@ArcticSnowman can you elaborate on why do you think the issue may not be fully resolved?

**Comment by ArcticSnowman** [comment]
The teams here using Sentry are occasionally seeing the same issue where the slack notifications shows the previous events message.    

For these events: 
<img width="725" alt="Sentry EVents" src="https://user-images.githubusercontent.com/13837922/68131509-2dc27880-feeb-11e9-8e1a-048d09cddf50.png">

We only saw notification for the `Sep 18, 2019 1:34:52 PM UTC`, `Oct 20, 2019 10:25:47 PM UTC`, and  `Oct 31, 2019 5:53:39 PM UTC` events.  With the Oct 20th and Oct 31st having the message from the previous one.

This is the message for `Oct 31, 2019 5:53:39 PM UTC` (Not the slack time is in local EST)
<img width="689" alt="Annotation 2019-11-04 095014" src="https://user-images.githubusercontent.com/13837922/68131779-a0335880-feeb-11e9-9de6-8ba32ed8ef55.png">

Sentry is showing this
![image](https://user-images.githubusercontent.com/13837922/68132089-1932b000-feec-11e9-8119-c3bb85416888.png)

**Comment by ArcticSnowman** [comment]
@BYK - Any feedback?

**Comment by danieljheetch** [comment]
I can confirm this is still an issue today. The slack message's title is from a previous event, not the event of the slack message.

**Comment by MeredithAnya** [comment]
@danieljheetch 

> I can confirm this is still an issue today

Is this also for on-premise sentry ? or are you saying that you are seeing this behavior with sentry.io ?

This PR https://github.com/getsentry/sentry/pull/14464 _looks_ like it would have fixed things and was added after #12881.
