### ISSUE TITLE
webhook not work

### ISSUE THREAD

**Issue by TinkerDeng** [getsentry/sentry#14502]
when received a bug ，the webhook doesn't work。 when i click test plugin ,the webhook is execution。  
![image](https://user-images.githubusercontent.com/18025615/63680947-48aba900-c827-11e9-9a72-d13bd7a83f8e.png)

**Comment by alejandroduquec** [comment]
Pai yo tengo el mismo error

**Comment by alejandroduquec** [comment]
Same

**Comment by SagiMedina** [comment]
Same here

**Comment by eladtamari** [comment]
not working!
when testing plugin its working but when a real error received , notification wasn't sent

**Comment by scefali** [comment]
Thanks for writing in. Getting alerts from a webhook is not as simple as enabling the webhook plugin. You also have to configure an alert rule and set the action to `Send a notification (for all legacy integrations)`. The conditions you receive a webhook event are determined by the rules. For more documentation see: https://docs.sentry.io/workflow/notifications/alerts/

I just did a simple test and can confirm that once the alert rule is set up, I get the webhook event.

If you have already configured an alert rule but it's still not working, please post your configuration here so I can help debug the issue.

**Comment by SagiMedina** [comment]
@scefali Thanks!
Still, haven't got it to work
Here is my alert configuration:
**Every time any of these conditions are met:**
Av event's level is greater than or equal to debug
**In this environment:**
All Environments
**Take these actions:**
Send a notification (for all legacy integrations)
**Perform these actions at most once every 30 minutes for an issue**

**DIGESTS**
Minimum delivery interval: 1 minute
Maximum delivery interval: 2 minutes

**Sentry version: 10.0.0.dev0 on-promise**

**Comment by Tang-RoseChild** [comment]
same

**Comment by BYK** [comment]
This is fixed by https://github.com/getsentry/onpremise/pull/309

You can update your copy of on-premise and run `docker-compose up -d` and the new service will be brought up, fixing the issues.

**Comment by simbawus** [comment]
What about the Stable for Sentry 9.1.2  version?

**Comment by BYK** [comment]
@simbawus we won't be releasing a new version of Sentry 9.1 so I'd keep my eye on the v10 release which is very soon.

**Comment by rishabsharma23** [comment]
Looks like the issue still persists. Webhook is not working even when alerts are enabled.

**Comment by natuan62** [comment]
Same isssue, when click test plugin ,the webhook is work fine
But when sentry create new issue or anything etc, webhook still not working

**Comment by BYK** [comment]
@natuan62 can you please file a new issue by following the issue template which would provide us all the relevant information to diagnose what might be going wrong?
