### ISSUE TITLE
Unable to view projects and errors on fresh docker desktop deployment

### ISSUE THREAD

**Issue by multinerd** [getsentry/sentry#16761]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [10.1.0.dev0 1e17bb4]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Unable to view projects and errors on fresh docker desktop deployment

## Steps to Reproduce

1. Configured settings: 
sentry.conf.py: 
```python
# Commented out
# GITHUB_EXTENDED_PERMISSIONS = ['repo'] 
```

config.yml
```yml
// configured smtp settings
system.internal-url-prefix:'http://localhost:9000' // Was 'http://web:9000'
symbolicator.options:
  url: "http://localhost:3021" // Was "http://symbolicator:3021"
```

2. Run `install.sh`
3. On docker `*_web` ran `sentry upgrade`
4. Login to `http://localhost:9000/`

![image](https://user-images.githubusercontent.com/6367998/73600863-c38a9580-4524-11ea-88d3-efa21138ca0e.png)

Good items to include here include:

```log
web_1 | 23:58:14 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/organizations/sentry/events/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:14 +0000] "GET /organizations/sentry/events/ HTTP/1.1" 200 4841 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:15 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/internal/health/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | 23:58:15 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/?member=1' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:15 +0000] "GET /api/0/internal/health/ HTTP/1.1" 200 1185 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:15 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/?detailed=1' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:15 +0000] "GET /api/0/organizations/?member=1 HTTP/1.1" 200 1898 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:15 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/assistant/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:15 +0000] "GET /api/0/assistant/ HTTP/1.1" 200 3379 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:15 +0000] "GET /api/0/organizations/sentry/?detailed=1 HTTP/1.1" 200 3466 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:15 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/broadcasts/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:15 +0000] "GET /api/0/organizations/sentry/broadcasts/ HTTP/1.1" 200 1101 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:15 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/projects/?per_page=50' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | 23:58:15 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/tags/?statsPeriod=14d&use_cache=1' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

snuba-api_1 | 2020-02-01 23:58:15,912 Error running query: SELECT (arrayJoin(tags.key) AS tags_key), (count() AS count) FROM sentry_local SAMPLE 1 PREWHERE project_id IN (1) WHERE project_id IN (1) AND timestamp >= toDateTime('2020-01-18T23:58:15') AND timestamp < toDateTime('2020-02-01T23:58:15') AND deleted = 0 GROUP BY (tags_key) ORDER BY count DESC LIMIT 0, 1000

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:15 +0000] "GET /api/0/organizations/sentry/projects/?per_page=50 HTTP/1.1" 200 1951 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:16 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/events/?statsPeriod=14d' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

snuba-api_1 | 2020-02-01 23:58:16,093 Error running query: SELECT event_id, project_id, timestamp FROM sentry_local PREWHERE project_id IN (1) WHERE project_id IN (1) AND timestamp >= toDateTime('2020-01-18T23:58:16') AND timestamp < toDateTime('2020-02-01T23:58:16') AND deleted = 0 ORDER BY timestamp DESC, event_id DESC LIMIT 0, 101

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:15 +0000] "GET /api/0/organizations/sentry/tags/?statsPeriod=14d&use_cache=1 HTTP/1.1" 500 702 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:16 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/events-stats/?interval=30m&query=&statsPeriod=28d' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

snuba-api_1 | 2020-02-01 23:58:16,182 Error running query: SELECT (toDateTime(intDiv(toUInt32(timestamp), 1800) * 1800) AS time), (count() AS count) FROM sentry_local PREWHERE project_id IN (1) WHERE project_id IN (1) AND timestamp >= toDateTime('2020-01-04T23:58:16') AND timestamp < toDateTime('2020-02-01T23:58:16') AND deleted = 0 GROUP BY (time) ORDER BY time ASC LIMIT 0, 10000

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:15 +0000] "GET /api/0/organizations/sentry/events/?statsPeriod=14d HTTP/1.1" 500 702 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:16 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/releases/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

snuba-api_1 | 2020-02-01 23:58:16,414 Error running query: SELECT project_id, (`sentry:release` AS `tags[sentry:release]`), (count() AS times_seen), (min(timestamp) AS first_seen), (max(timestamp) AS last_seen) FROM sentry_local PREWHERE `tags[sentry:release]` IN ('1e17bb461d26999c5cd89f6f2e274923ce0010d9') WHERE project_id IN (1) AND timestamp >= toDateTime('2019-11-03T23:58:16') AND timestamp < toDateTime('2020-02-01T23:58:17') AND deleted = 0 GROUP BY (project_id, `tags[sentry:release]`) LIMIT 0, 1000

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:16 +0000] "GET /api/0/organizations/sentry/events-stats/?interval=30m&query=&statsPeriod=28d HTTP/1.1" 500 702 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 23:58:16 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/1/store/?sentry_key=bf9384e555e743f8b6253219f9fdd9a5&sentry_version=7' method=u'POST' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:16 +0000] "POST /api/1/store/?sentry_key=bf9384e555e743f8b6253219f9fdd9a5&sentry_version=7 HTTP/1.1" 200 1149 "http://localhost:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [01/Feb/2020:23:58:16 +0000] "GET /api/0/organizations/sentry/releases/ HTTP/1.1" 500 714 "http://localhost:9000/organizations/sentry/events/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
```
- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

### What you expected to happen

The project i created and the event that should be posted to appear

### Possible Solution

Might be related to #16723 

Similar problem when looking at `Projects` tab:

![image](https://user-images.githubusercontent.com/6367998/73600887-3f84dd80-4525-11ea-8020-942a656aad53.png)

```log
web_1 | 00:02:02 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/organizations/sentry/projects/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:02 +0000] "GET /organizations/sentry/projects/ HTTP/1.1" 200 4838 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:02 +0000] "GET /_static/1580600596/sentry/dist/vendor.js HTTP/1.1" 304 226 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:02 +0000] "GET /_static/1580600596/sentry/dist/sentry.css HTTP/1.1" 304 194 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:02 +0000] "GET /_static/1580600596/sentry/dist/app.js HTTP/1.1" 304 226 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:02 +0000] "GET /_static/1580600596/sentry/js/ads.js HTTP/1.1" 304 226 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /_static/1580600596/sentry/dist/sentry-loader.gif HTTP/1.1" 304 194 "http://localhost:9000/_static/1580600596/sentry/dist/sentry.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/?member=1' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/internal/health/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/internal/health/ HTTP/1.1" 200 1186 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/?detailed=0' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/organizations/?member=1 HTTP/1.1" 200 1899 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/assistant/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/assistant/ HTTP/1.1" 200 3380 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/organizations/sentry/?detailed=0 HTTP/1.1" 200 2641 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/projects/?all_projects=1' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/teams/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/organizations/sentry/projects/?all_projects=1 HTTP/1.1" 200 1672 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/organizations/sentry/teams/ HTTP/1.1" 200 2031 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/broadcasts/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/user-teams/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/organizations/sentry/broadcasts/ HTTP/1.1" 200 1102 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/organizations/sentry/user-teams/ HTTP/1.1" 200 1763 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/teams/sentry/sentry/members/' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/teams/sentry/sentry/members/ HTTP/1.1" 200 2989 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/projects/?statsPeriod=24h&query=id%3A1' method=u'GET' ip_address=u'{MY_IP_ADDRESS}')

snuba-api_1 | 2020-02-02 00:02:03,852 Error running query: SELECT project_id, (toStartOfHour(timestamp) AS time), (count() AS aggregate) FROM sentry_local PREWHERE project_id IN (1) WHERE project_id IN (1) AND timestamp >= toDateTime('2020-02-01T01:00:00') AND timestamp < toDateTime('2020-02-02T01:00:00') AND deleted = 0 GROUP BY (project_id, time) LIMIT 0, 24

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "GET /api/0/organizations/sentry/projects/?statsPeriod=24h&query=id%3A1 HTTP/1.1" 500 702 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"

web_1 | 00:02:03 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/1/store/?sentry_key=bf9384e555e743f8b6253219f9fdd9a5&sentry_version=7' method=u'POST' ip_address=u'{MY_IP_ADDRESS}')

web_1 | {MY_IP_ADDRESS} - - [02/Feb/2020:00:02:03 +0000] "POST /api/1/store/?sentry_key=bf9384e555e743f8b6253219f9fdd9a5&sentry_version=7 HTTP/1.1" 200 1150 "http://localhost:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
```

**Comment by multinerd** [comment]
calling `http://localhost:9000/api/0/organizations/sentry/projects/?statsPeriod=24h&query=id%3A1` results in 

```json
{
  "detail": "Internal Error",
  "errorId": "17bb77164a4b471998a378b987cdb69c"
}
```

im not sure how to view the log files. Once i do, ill provide more info

**Comment by BYK** [comment]
Why are you changing these configuration values? Seems like you are not running Snuba or it is unreachable to Sentry?

**Comment by multinerd** [comment]
I changed `system.internal-url-prefix` because I was not able to access sentry from `http://web:9000` without modifying my host file.
Changing it to `http://localhost:9000` allowed me to view my local instance in a web browser. 

For `symbolicator.options`, I assumed leaving it as `http://symbolicator:3021` would have the same issue as above, so I also changed that to `localhost`.

I should add that I was able to get an instance up and running with these configurations, and fully tested with a demo c# application, thought this was a few days ago.

Yesterday, I decided to set up a development instance on a different machine, doing exactly what I did the first time, and that's when i started getting the errors shown above. The only difference i noticed yesterday was the build version. Apparently `onpremise` pulls directly from github, rather than a stable build and the lack of any type of *versioning* made me give up on it entirely, but i digress. 

Are those values not supposed to be changed? I don't know of any situation where `http://web:9000/` will resolve on my local machine unless I modify my host file and point `web` to something.

**Comment by BYK** [comment]
>I changed system.internal-url-prefix because I was not able to access sentry from http://web:9000 without modifying my host file.
Changing it to http://localhost:9000 allowed me to view my local instance in a web browser.

As the name suggests, this is for _internal_ use. Changing it to `localhost` simply broke your Symbolicator integration.

>For symbolicator.options, I assumed leaving it as http://symbolicator:3021 would have the same issue as above, so I also changed that to localhost.

See above, same reason. These are Docker Compose service names that automatically get resolved by Docker's internal DNS. These are not external values nor should they be changed.

>I should add that I was able to get an instance up and running with these configurations, and fully tested with a demo c# application, thought this was a few days ago.

This is expected as the breakage would only happen when you try to use Symbolicator, which happens when you upload debug symbols.

>Apparently onpremise pulls directly from github, rather than a stable build and the lack of any type of versioning made me give up on it entirely, but i digress.

All builds have the same stability guarantees as we don't do any extra manual testing for any versions we tag. They are already vetted by our automated tests and deploys to sentry.io.

I'd just check the logs for the `snuba-api` service which should provide us more information.

**Comment by multinerd** [comment]
Ok, I did a prune on docker and ran `install.sh`, allowing it to create new config files, all unmodified.

I am still getting internal errors.

It looks like a Db error on table `sentry_option`


Here is what shows up in `sentry_onpremise_snuba-api_1`

```log
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 214, in execute

columnar=columnar

File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 334, in process_ordinary_query

columnar=columnar)

File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 83, in receive_result

return result.get_result()

File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/result.py", line 48, in get_result

for packet in self.packet_generator:

File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 95, in packet_generator

packet = self.receive_packet()

File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 112, in receive_packet

raise packet.exception

clickhouse_driver.errors.ServerException: Code: 60.

DB::Exception: Table default.sentry_local doesn't exist.. Stack trace:


0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x7dd0490]

1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x25) [0x3bf8a05]

2. /usr/bin/clickhouse-server(DB::Context::getTableImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Exception*) const+0x3fd) [0x6c6622d]

3. /usr/bin/clickhouse-server(DB::Context::getTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x81) [0x6c66421]

4. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x11d4) [0x6ccb5c4]

5. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x37) [0x6ccb757]

6. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x7e8) [0x6cdc9a8]

7. /usr/bin/clickhouse-server(DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum)+0x1b8) [0x6cac458]

8. /usr/bin/clickhouse-server() [0x6ddff55]

9. /usr/bin/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)+0x74) [0x6de00e4]

10. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x8bd) [0x3c02dfd]

11. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x3c034cb]

12. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0x10) [0x77ab320]

13. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xed) [0x77aba3d]

14. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x7ecf1e1]

15. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x3c) [0x7eccf8c]

16. /usr/bin/clickhouse-server() [0xb8a2700]

17. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f61896bb6db]

18. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f6188e4288f]

2020-02-03 20:51:34,589 Error running query: SELECT (toDateTime(intDiv(toUInt32(timestamp), 1800) * 1800) AS time), (count() AS count) FROM sentry_local PREWHERE project_id IN (2, 1) WHERE project_id IN (1, 2) AND timestamp >= toDateTime('2020-01-06T20:51:34') AND timestamp < toDateTime('2020-02-03T20:51:34') AND deleted = 0 GROUP BY (time) ORDER BY time ASC LIMIT 0, 10000



Code: 60.

Traceback (most recent call last):

File "./snuba/web/query.py", line 140, in raw_query

with_totals=request.query.has_totals(),

File "./snuba/clickhouse/native.py", line 171, in execute

sql, with_column_types=True, settings=settings, **kwargs

File "./snuba/clickhouse/native.py", line 60, in execute

result = conn.execute(*args, **kwargs)
```

and `sentry_onpremise_postgres_1`

```log
ERROR: relation "sentry_option" does not exist at character 114

STATEMENT: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = 'system.url-prefix'

STATEMENT: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = 'auth.allow-registration'

STATEMENT: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = 'sentry:latest_version'

ERROR: relation "sentry_projectkey" does not exist at character 371

STATEMENT: SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = 1 AND "sentry_projectkey"."roles" = (("sentry_projectkey"."roles" | 1))) LIMIT 1

STATEMENT: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = 'github.apps-install-url'

ERROR: relation "south_migrationhistory" does not exist at character 15

STATEMENT: SELECT 1 FROM south_migrationhistory LIMIT 1

ERROR: relation "sentry_organization" does not exist at character 237

STATEMENT: SELECT "sentry_organization"."id", "sentry_organization"."name", "sentry_organization"."slug", "sentry_organization"."status", "sentry_organization"."date_added", "sentry_organization"."default_role", "sentry_organization"."flags" FROM "sentry_organization" WHERE "sentry_organization"."status" = 0 LIMIT 1

STATEMENT: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= '2020-02-03T19:47:27.280138+00:00'::timestamptz

STATEMENT: SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = 1 AND "sentry_projectkey"."status" = 0 AND "sentry_projectkey"."roles" = (("sentry_projectkey"."roles" | 1))) ORDER BY "sentry_projectkey"."id" ASC LIMIT 1

STATEMENT: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= '2020-02-03T19:47:37.279568+00:00'::timestamptz

STATEMENT: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= '2020-02-03T19:47:47.304228+00:00'::timestamptz

STATEMENT: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= '2020-02-03T19:47:57.315241+00:00'::timestamptz
```


`sentry_onpremise_worker_1`
```log
ProgrammingError: UndefinedTable('relation "sentry_option" does not exist\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\n ^\n',)
```

**Comment by BYK** [comment]
Sounds like your installation got interrupted. Can you share your install logs please?

**Comment by multinerd** [comment]
[sentry_install_log-2020-02-03_16-10-39.txt](https://github.com/getsentry/sentry/files/4150238/sentry_install_log-2020-02-03_16-10-39.txt)

**Comment by BYK** [comment]
Here's your problem:
```
[3028] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 865, in run
  File "compose\cli\main.py", line 1349, in run_one_off_container
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
```

Check your environment and your `.env` file to make this error go away. Closing this issue as it is related to your environment, which causes the Snuba bootstrap and database upgrade/init steps to not run.

**Comment by multinerd** [comment]
Thanks for your help. Turns out, the problem was with `docker-compose`. Updating to `1.25.4` allowed the install.sh file to run to completion. 

https://github.com/docker/compose/issues/7169
