### ISSUE TITLE
"You need to link your account with the SSO provider to continue" is always displayed at login

### ISSUE THREAD

**Issue by Rambomst** [getsentry/sentry#2576]
Sentry 8.0.2

We are using Google SSO for Sentry and every time I go to Sentry after being inactive for awhile it will redirect me to a login screen which says "You need to link your account with the SSO provider to continue." and has a button which says "Login with Google". I am not sure if the account hasn't linked correctly or that message just needs to be hidden.

**Comment by dcramer** [comment]
@Rambomst just to confirm, you actually linked the account, correct?

If you're a superuser it lets you bypass this requirement in some situations.

**Comment by Rambomst** [comment]
Yes I linked the account, as it filled in my real name and what not.

This happens to others within our office as well not just me.

**Comment by dcramer** [comment]
If you look at the members tab do you happen to see duplicate accounts?






On Mon, Jan 25, 2016 at 3:24 PM -0800, "Rambomst" <notifications@github.com> wrote:












Yes I linked the account, as it filled in my real name and what not.



This happens to others within our office as well not just me.

**Comment by Rambomst** [comment]
There are no duplicates within the "Members" area.

**Comment by chebelom** [comment]
+1

**Comment by matino** [comment]
Having this issue as well with 8.5.0.dev0

**Comment by dcramer** [comment]
@matino SHA? We just pushed a couple of fixes for sentry-auth-github as well as improved error reporting in master.

**Comment by matino** [comment]
I'm using https://app.getsentry.com/

**Comment by dcramer** [comment]
I'm going to close this out. Let me know if you're still having issues on app.getsentry.com.

**Comment by chebelom** [comment]
I am still having this issue: I am using the official [docker image 8.6.0-onbuild](https://github.com/getsentry/docker-sentry/blob/09d2b56ded2f669f40d5295bfe36529bbafb914d/8.6/onbuild/Dockerfile).
In the Member page I can see "Missing SSO Link - Resend invite" for all our users.

**Comment by mattrobenolt** [comment]
Did you configure install an SSO backend?

**Comment by chebelom** [comment]
@mattrobenolt , thanks for your quick answer.
yes I followed this guide https://docs.getsentry.com/on-premise/learn/sso/ and we can login with it just fine.
It just shows the red banner all the time and asks to login very often

**Comment by marcomorain** [comment]
We are getting a similar issue. We have some SSO members (Google auth) and some non-SSO. The non SSO members all have "missing SSO link" beside them

**Comment by nttdocomo** [comment]
I have the same issue. I have link the sso. but after I login for a while., maybe 1 or 2 hours. when I refresh the page, it ask me to login with click a button with "Login with XXXXX"

**Comment by dcramer** [comment]
SSO isn’t expected to be optional. The option is to allow bypassing SSO, but the expectation is that all users still have an identity. We also currently do not expose a Non-SSO login form on the organization login page when SSO is enabled. The latter is something we’ve talked about implementing but it doesn’t change the core approach to SSO.

**Comment by npockrus-bnet** [comment]
I am also having the same issue using this plugin for in-house auth: https://pypi.org/project/sentry-auth-oidc/

I verified the emails match. They are properly routed to the SSO login page and login through that but the SSO link missing message still shows under their user

**Comment by davvilla** [comment]
Hello, I'm getting the same issue using https://github.com/getsentry/sentry-auth-google and sentry 9.1.1
