### ISSUE TITLE
Cron monitoring CSRF Verification Failed

### ISSUE THREAD

**Issue by kritik** [getsentry/sentry#45690]
### Environment

SaaS (https://sentry.io/)

### Link

'https://sentry.io/api/0/organizations/{scope}/monitors/{MONITOR_ID}/checkins/

### DSN

https://50240cb9d68d4d8bb1a2cdd284b28126@o1315766.ingest.sentry.io/6567865

### Steps to Reproduce

1. go to https://docs.sentry.io/product/crons/getting-started/#step-2-set-up-health-checks
2. copy first curl
3. replace monitor_id
4. run in the console
5. response in html <title>CSRF Verification Failed | Sentry</title>

### Expected Result

response returns 
1. in json
3. HTTP/1.1 200

### Actual Result

response returns 
1. error in html
2. title is <title>CSRF Verification Failed | Sentry</title>
3. HTTP/1.1 403 Forbidden

**Comment by ryskov** [comment]
+1

**Comment by Admiral-Enigma** [comment]
+1

**Comment by cleptric** [comment]
We're looking into it right now

**Comment by cleptric** [comment]
We released a new version on production that should fix this issue.
Thanks for your patience!

**Comment by doudejans** [comment]
Shouldn't the PUT endpoint to update the checkin status also be `csrf_exempt`? https://github.com/getsentry/sentry/commit/0e9c3656f7efc99435cf08c97c49be2ccf7fcf5d#diff-0568d2568ed366405103d213b7ba1291a283f1e517375416fb758ffd41f308f0R1341-R1347

The initial checkins are now working for us again, but the status update is still failing with the same CSRF error, which makes the cron monitors fail based on duration.

**Comment by davidenwang** [comment]
ahh yes updating the PUT endpoint too now

**Comment by cleptric** [comment]
The fix for the PUT endpoint was released as well. Let us know if you encounter any other issues.
