### ISSUE TITLE
Transaction Alerts | Transactions filtered for devices do not collect data

### ISSUE THREAD

**Issue by andyl-ioki** [getsentry/sentry#58753]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a transaction with a specific device, e.g. `device:SM-A226B`
2. Note the warning icon next to the filter input which states:
    > We don't routinely collect metrics from "**device**". However, we do so **once this alert has been saved**.
3. Save the alert.
4. Check the alert and see in the `Transaction Duration` part that the "Summary" shows `100%` for the clock icon - "The time spent waiting for metrics matching the filters used."

---

**Note:**
We made sure that the tag `device:SM-A226B` and is available for our project. So there are users with this specific device and transactions gathered with it.
We tried also other tags like `app.device` with the same result.

This is related to an [issue](https://github.com/getsentry/sentry/issues/54672) I created earlier. Since then it only showed me the empty graph. I thought that it will change over time, but it does not. :( 

### Expected Result

After a short while the page shows data in the alert graph.
Alerts are triggered (if necessary) properly.

### Actual Result

Transactions graph of the alert stays empty (for weeks).
Waiting time stays at 100%.
<img width="715" alt="Screenshot 2023-10-25 at 12 00 49" src="https://github.com/getsentry/sentry/assets/102946449/4b0f68d4-4e3b-4fdb-8d97-ea6721f079cd">

When clicking on "Open in Discover" you can see a proper graph:
<img width="776" alt="Screenshot 2023-10-25 at 12 02 48" src="https://github.com/getsentry/sentry/assets/102946449/89a54e0d-02ac-4eab-9f8d-891ae4d795e0">

When getting back to edit the rule, even there a proper data graph is shown, with a small information noting "The chart data above is an estimate based on the stored transactions that match the filters specified.":
<img width="776" alt="Screenshot 2023-10-25 at 12 04 54" src="https://github.com/getsentry/sentry/assets/102946449/0ffdf97f-0f56-4d99-9897-7c3314c6dea9">

**Note:**
I created very low thresholds for this alert to test if at least they trigger, but they didn't. :( 

### Product Area

Alerts

**Comment by roggenkemper** [comment]
thanks for bringing this up again! i've reached out to the team in charge of this project to get an answer for you.

**Comment by andyl-ioki** [comment]
We are receiving now data.
Thanks so much!

**Comment by andyl-ioki** [comment]
Unfortunately I have to reopen this issue again.
It was working for me at that time, when I wrote the comment above ☝️ 

But since then I did not have the chance to see the correct view again. It is like described in the issue again. No data at all and waiting time stays at 100%. :(

Maybe I switched your A/B Testing group and did not get back in there? :D 

@roggenkemper can you check that again?

**Comment by matejminar** [comment]
Hey @andyl-ioki , this should be fixed as soon as https://github.com/getsentry/relay/pull/2728 is deployed. 👍

**Comment by andyl-ioki** [comment]
Cool. Thanks for the reply.

**Comment by matejminar** [comment]
@andyl-ioki Can you confirm it's working now?

**Comment by andyl-ioki** [comment]
Hej @matejminar,

All in all: No, it is not working :(

In detail:
Yesterday I checked the existing alert. Rechecked it today as well. I also modified the alert and checked it again after couple of hours. It is still not showing any graph/data. (When I edit the alert, it shows a striped graph with the info that the data is not yet collected but then after saving the modifications of the rule)

I also created a new rule today, with the same filters ... no luck. I also can't see the striped graph. It's just empty.

**Comment by matejminar** [comment]
I'll have a chat with our ingest team. Everything else looks good from a product standpoint. Sorry for any inconvenience caused.

**Comment by andyl-ioki** [comment]
Thanks for the fast reply and taking care of it 👍 
I will let you know if something changes on our "Alert" side.

**Comment by obostjancic** [comment]
Hi @andyl-ioki We have taken a closer look at this, and have a suspicion that it is related to the environment filter condition. In order to verify that, would you mind temporarily editing the alert to target "All environments" instead of the currently selected one. It should take a couple of minutes to propagate the change, but after that you should start seeing the data come in.

**Comment by andyl-ioki** [comment]
@obostjancic I will have a look now 👀

**Comment by andyl-ioki** [comment]
@obostjancic 
Sorry for my late reply.

I have good news - when I removed the filter for the environment the graph starts to show up 🎉 
<img width="773" alt="Screenshot 2023-11-24 at 06 41 55" src="https://github.com/getsentry/sentry/assets/102946449/a3b467a8-3a75-4f47-8cda-102b3d0caaf0">

I don't know if the warning and critical messages behave correctly, but we will see.

**Comment by obostjancic** [comment]
@andyl-ioki Great! 🎉  The fix for environment filter should then land with #59995. I'll link this issue to it, so that you get notified when it's merged.
