### ISSUE TITLE
Jira ticket constantly reopened

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#62565]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

0. Link two issues to the same Jira ticket.  Merge them.
1. Go to the Jira ticket linked to both issues.
2. Mark as `Done` (the state matching `Resolved` in Senry)
3. Sentry issue 93 (the "parent" issue of the merge) is marked as resolved.
4. Wait some time
5. The Jira ticket is reopened, as well as the Sentry issue 93, but issue has not presented itself in any new version.

https://dropbox.sentry.io/issues/4683300905/?project=4505546600087552

### Expected Result

When ticket marked as done and ticket resolved in Jira, the ticket and matching Sentry issue should both remain resolved until a regression is seen.

### Actual Result

The Jira ticket is reopened, as well as the Sentry issue 93, but issue has not presented itself in any new version.

Can't tell why the ticket is reopened in either Jira or Sentry, see #61878 for details of that issue.

My theory is that the merged issue (N2) is still affecting the Jira ticket, as I was seeing this behavior before I merged N2 into 93, but I cannot be sure it's still the reason.  N2 would say it reopened the ticket, then 93 would reopen in response to the Jira ticket reopening.

See slack threads between DBX + Sentry: 
https://dropbox.slack.com/archives/C04VDU7UZQE/p1704300001959139
https://sentry.slack.com/archives/C04VDU7UZQE/p1702678332601749?thread_ts=1702599116.070419&cid=C04VDU7UZQE

### Product Area

Issues

### Link

https://dropbox.sentry.io/issues/4683300905/?project=4505546600087552

**Comment by realkosty** [comment]
Related: https://github.com/getsentry/sentry/issues/61878

**Comment by realkosty** [comment]
Note this is being observed with Jira Server integration. Unknown whether it affects other issue tracking integrations or not.

**Comment by jboulter11** [comment]
As far as I can tell, nothing on our Jira side is flipping it back.  This jira ticket was also linked to other issues in the past (we were iterating on some grouping fixes with y'all), so maybe it's possible there's some other link that is setting it back?  If we can get an update that posts more info to Jira on changes, maybe that'll just tell us the problem?

**Comment by scttcper** [comment]
@jboulter11 we've made it a bit more clear which integration is making the change if you want to try to resolve the issue again.

![image](https://github.com/getsentry/sentry/assets/1400464/717d9175-a6da-44f1-9135-96afba1ec2ed)

**Comment by jboulter11** [comment]
I tried again and it doesn't say anything helpful.  The Jira ticket gets kicked back to triage by the Sentry integration but doesn't say why.  That triggers Sentry to reopen the issue.  So no new info from the change.

I'd like it to tell me exactly which Jira ticket triggered the change via that integration and why.  I'd also like to see the same reflected in Jira on the ticket, a comment stating exactly which Sentry Issue is causing the change in resolution and why.

Examples:
In Sentry: 
> Sentry marked this issue as resolved via Jira: IOSDBAPP-1234 was marked as Done by Jim Boulter
In Jira:
> Sentry reopened this issue because it was seen by DROPBOX-IOS-93 in version 350.1.2 and its fix version was 348.2.2.

Where IOSDBAPP-1234 is the jira ticket id and DROPBOX-IOS-93 is the Sentry issue id

**Comment by realkosty** [comment]
I just tested the following scenario:

1. Linked Sentry issue `A` to Jira issue `JIRA-A`
2. Linked `B` to `JIRA-B` 
3. Merged `B` into `A`
4. ⚠️ resulting issue only shows `JIRA-A`, `JIRA-B` is seemingly discarded. This is consistent with Sentry not allowing to link same Sentry issue to more than 1 Jira issue from the same Jira project (regardless of merging).
5. Resolve `JIRA-B`. Wait more over 2 hours.
6. **`A` stays unresolved.** `JIRA-B` stays resolved.
7. Resolve `JIRA-A`
8. **`A` resolved almost immediately** via Jira.
9. Link a third, unresolved, Sentry issue `C` to `JIRA-A`.
10. **`A` immediately becomes unresloved again.**

So no shadow linking bugs but will get reopened transitively when an open Sentry issue is linked to a closed Jira issue that's linked to another closed Sentry issue.

**Comment by lobsterkatie** [comment]
@realkosty - Thanks for the thorough testing!

To clarify, had you resolved `JIRA-B` and/or `B` before the merge? Or did `B` get resolved by resolving `JIRA-B`, even though the link between the two was seemingly broken by the merge?

**Comment by jboulter11** [comment]
Correction here, there is no `JIRA-B`, only `JIRA-A` in this scenario.  Both `A` and `B` hook up to `JIRA-A`.

**Comment by jboulter11** [comment]
1. Linked Sentry issue `A` to Jira issue `JIRA-A`
3. Linked `B` to `JIRA-A`
4. Merged `B` into `A`
5. Resolve `JIRA-A`.  `A` resolves in Sentry. Wait 15-30min
6. `???` (maybe `B`?) reopens `JIRA-A`.
7. `A` reopens in Sentry

**Comment by realkosty** [comment]
@jboulter11 
Sorry for confusion: I intentionally tested a broader scenario because we can't reproduce the one you described => there must be something else going on here
 
@lobsterkatie 
> To clarify, had you resolved JIRA-B and/or B before the merge? Or did B get resolved by resolving JIRA-B, even though the link between the two was seemingly broken by the merge?

No, in the beginning all 4 Sentry and Jira issues are open. `JIRA-B` gets resolved in step 5, already after B is merged into A (step 3). By the time `JIRA-B` is resoled, B doesn't exist any more.

**Comment by lobsterkatie** [comment]
@realkosty - Okay, so that tells us something, which is the link between `B` (now part of `A) and `JIRA-B` still exists, which is interesting. 

(@jboulter11 , I get that's not what's happening for you. In your case, I checked our database, and that same Jira issue is also linked to this Sentry issue: https://dropbox.sentry.io/issues/4578273282/, which is unresolved. Are you aware of that? Could that be the cause of the confusion?)

**Comment by realkosty** [comment]
@lobsterkatie wait, does it? I made the opposite conclusion

**Comment by jboulter11** [comment]
> (@jboulter11 , I get that's not what's happening for you. In your case, I checked our database, and that same Jira issue is also linked to this Sentry issue: https://dropbox.sentry.io/issues/4578273282/, which is unresolved. Are you aware of that? Could that be the cause of the confusion?)

OHhhhhh!  This is huge!  This is exactly the kind of thing that would be glaringly obvious if the comment posted to Jira included that info I mentioned!  I'd bet it's that.  I'm gonna un-hook that up and try resolving!

**Comment by lobsterkatie** [comment]
Great - hopefully that fixes it!

I'm curious - when you look at the issue in Jira, does it only show the one Sentry issue? I found one of our Jira tickets which is linked to multiple sentry issues, and it shows them both. 

![image](https://github.com/getsentry/sentry/assets/14812505/96ffb5a3-09a0-41c4-b0fb-025df4e061a8)
![image](https://github.com/getsentry/sentry/assets/14812505/fdde9664-3587-47e5-a66c-20ea47e8fc23)

**Comment by lobsterkatie** [comment]
> This is exactly the kind of thing that would be glaringly obvious if the comment posted to Jira included that info I mentioned!

FYI, I included that in an issue I wrote up earlier, so it wouldn't fall off our radar: https://github.com/getsentry/sentry/issues/62797

**Comment by lobsterkatie** [comment]
> @lobsterkatie wait, does it? I made the opposite conclusion

@realkosty - Oh, dang, you're right. I misread your original list of steps. Disregard, sorry!

**Comment by jboulter11** [comment]
So this definitely fixed the issue, it did not reopen overnight! :D 

Since we're on Jira Server (what have I done to deserve this hell?) and not Jira Cloud, I have no view that resembles the one you screenshotted.  Best I had was a few comments about some attached sentry tickets which I had checked through.  However, I forgot to double check the issue which was _initially_ attached to this ticket (`F`, the one you linked) was also not attached still.  So basically my fault, but short of me realizing I needed to check the original ticket was not attached, there was not really a great way of alerting me to what was going on.

I greatly look forward to #62797 and I am happy to help you test, give any feedback you need, etc.  Just let me know how I can help out. :) 

Thank you!
