### ISSUE TITLE
Release creation inconsistently results 404

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#63816]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Make sure you set up the latest version of `sentry-cli`
2. Follow [this documentation](https://docs.sentry.io/product/cli/releases/#creating-releases) to create a new release
3. Then use the [create a deploy command](https://docs.sentry.io/product/cli/releases/#creating-deploys)
4. Run the command above a couple of times

### Expected Result

This command succeeds every time.

### Actual Result

The command sometimes throws a 404 "release not found". There doesn't seem to be any pattern to when it is thrown, but a customer has noted that it has gotten more frequent this week.

This is seemingly occurring through bundlers too, like `@sentry/webpack-plugin`, `@sentry/vite-plugin` and `@sentry/esbuild-plugin` (all in the latest release at the time of writing, 2.10.3)

### Product Area

Releases

**Comment by jangjodi** [comment]
Hi @InterstellarStella, I was unable to replicate this issue. Could you please share what command they used?

**Comment by slestang** [comment]
Hi @jangjodi,

We are the impacted customer. An example of command that fail most of the time:

```
sentry-cli releases deploys spreadsheet-frontend@dev#99cf6a870-3853 new --env dev --auth-token sntrys_*** --log-level=debug
  DEBUG   2024-01-24 14:51:55.755832 +01:00 sentry-cli version: 2.26.0, platform: "darwin", architecture: "arm64"
  INFO    2024-01-24 14:51:55.756308 +01:00 sentry-cli was invoked with the following command line: "sentry-cli" "releases" "deploys" "spreadsheet-frontend@dev#99cf6a870-3853" "new" "--env" "dev" "--auth-token" "sntrys_***" "--log-level=debug"
  DEBUG   2024-01-24 14:51:55.756532 +01:00 request POST https://sentry.io/api/0/organizations/elements-apps/releases/spreadsheet-frontend@dev%2399cf6a870-3853/deploys/
  DEBUG   2024-01-24 14:51:55.756554 +01:00 using token authentication
  DEBUG   2024-01-24 14:51:55.756584 +01:00 json body: {"environment":"dev","name":null,"url":null,"dateStarted":null,"dateFinished":"2024-01-24T13:51:55.756489Z"}
  DEBUG   2024-01-24 14:51:55.756592 +01:00 retry number 0, max retries: 0
  DEBUG   2024-01-24 14:51:55.870638 +01:00 > POST /api/0/organizations/elements-apps/releases/spreadsheet-frontend@dev%2399cf6a870-3853/deploys/ HTTP/1.1
  DEBUG   2024-01-24 14:51:55.870681 +01:00 > Host: sentry.io
  DEBUG   2024-01-24 14:51:55.870688 +01:00 > Accept: */*
  DEBUG   2024-01-24 14:51:55.870693 +01:00 > Connection: TE
  DEBUG   2024-01-24 14:51:55.870698 +01:00 > TE: gzip
  DEBUG   2024-01-24 14:51:55.870704 +01:00 > User-Agent: sentry-cli/2.26.0
  DEBUG   2024-01-24 14:51:55.871947 +01:00 > Authorization: Bearer sntrys_e***
  DEBUG   2024-01-24 14:51:55.871957 +01:00 > Content-Type: application/json
  DEBUG   2024-01-24 14:51:55.871963 +01:00 > Content-Length: 108
  DEBUG   2024-01-24 14:51:56.036 +01:00 < HTTP/1.1 404 Not Found
  DEBUG   2024-01-24 14:51:56.036194 +01:00 < server: nginx
  DEBUG   2024-01-24 14:51:56.036221 +01:00 < date: Wed, 24 Jan 2024 13:51:56 GMT
  DEBUG   2024-01-24 14:51:56.036243 +01:00 < content-type: application/json
  DEBUG   2024-01-24 14:51:56.036265 +01:00 < vary: Accept-Encoding,Accept-Language, Cookie
  DEBUG   2024-01-24 14:51:56.036331 +01:00 < x-sentry-rate-limit-remaining: 38
  DEBUG   2024-01-24 14:51:56.036353 +01:00 < x-sentry-rate-limit-limit: 40
  DEBUG   2024-01-24 14:51:56.036459 +01:00 < x-sentry-rate-limit-reset: 1706104316
  DEBUG   2024-01-24 14:51:56.036709 +01:00 < x-sentry-rate-limit-concurrentremaining: 24
  DEBUG   2024-01-24 14:51:56.036770 +01:00 < x-sentry-rate-limit-concurrentlimit: 25
  DEBUG   2024-01-24 14:51:56.036794 +01:00 < content-language: en
  DEBUG   2024-01-24 14:51:56.037054 +01:00 < x-frame-options: deny
  DEBUG   2024-01-24 14:51:56.037074 +01:00 < x-content-type-options: nosniff
  DEBUG   2024-01-24 14:51:56.037092 +01:00 < x-xss-protection: 1; mode=block
  DEBUG   2024-01-24 14:51:56.037121 +01:00 < content-security-policy: frame-src app.pendo.io demo.arcade.software js.stripe.com sentry.io; media-src *; font-src * data:; default-src 'none'; object-src 'self'; style-src 'unsafe-inline' *; script-src 'self' 'unsafe-inline' 'report-sample' 'unsafe-eval' s1.sentry-cdn.com js.sentry-cdn.com browser.sentry-cdn.com statuspage-production.s3.amazonaws.com static.zdassets.com aui-cdn.atlassian.com connect-cdn.atl-paas.net js.stripe.com 'strict-dynamic' cdn.pendo.io data.pendo.io pendo-io-static.storage.googleapis.com pendo-static-5634074999128064.storage.googleapis.com; connect-src 'self' *.algolia.net *.algolianet.com *.algolia.io sentry.io *.sentry.io s1.sentry-cdn.com o1.ingest.sentry.io api2.amplitude.com app.pendo.io data.pendo.io reload.getsentry.net t687h3m0nh65.statuspage.io sentry.zendesk.com ekr.zdassets.com maps.googleapis.com; frame-ancestors 'self' *.sentry.io; base-uri 'none'; img-src blob: data: *; report-uri https://o1.ingest.sentry.io/api/54785/security/?sentry_key=f724a8a027db45f5b21507e7142ff78e&sentry_release=d17f2734f7df4b42bc5969fb1274d69073d91cae
  DEBUG   2024-01-24 14:51:56.037524 +01:00 < x-envoy-attempt-count: 1
  DEBUG   2024-01-24 14:51:56.037544 +01:00 < x-envoy-upstream-service-time: 42
  DEBUG   2024-01-24 14:51:56.037564 +01:00 < x-served-by: getsentry-web-rpc-production-857c578df9-cj4qv
  DEBUG   2024-01-24 14:51:56.037606 +01:00 < x-sentry-proxy-url: http://10.2.0.67:8999/api/0/organizations/elements-apps/releases/spreadsheet-frontend@dev#99cf6a870-3853/deploys/
  DEBUG   2024-01-24 14:51:56.038091 +01:00 < x-served-by: getsentry-control-web-default-common-production-6949b6f45bttlbl
  DEBUG   2024-01-24 14:51:56.038103 +01:00 < x-served-by: frontend-default-6f87467fcf-rz95q
  DEBUG   2024-01-24 14:51:56.038114 +01:00 < strict-transport-security: max-age=31536000; includeSubDomains; preload
  DEBUG   2024-01-24 14:51:56.038124 +01:00 < via: 1.1 google
  DEBUG   2024-01-24 14:51:56.038133 +01:00 < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  DEBUG   2024-01-24 14:51:56.038149 +01:00 < Transfer-Encoding: chunked
  DEBUG   2024-01-24 14:51:56.038316 +01:00 response status: 404
error: release not found
  INFO    2024-01-24 14:51:56.042276 +01:00 Skipping update nagger update check
```

All our build pipelines are currently red for 3 days in a row because of this issue :sob:

**Comment by malwilley** [comment]
@slestang I don't see any obvious reasons why this might be happening so I'll look into this more. If you could help out with some additional information to help get to the bottom of this:

- Is this an issue with a single project or multiple different projects?
- Do you know if the deploy is still created (despite the error response)?
- Is this behavior still happening and at what frequency?

**Comment by KevinCalmant** [comment]
Hello @malwilley , 

I take the liberty of answering on behalf of @slestang. 

1. This problem is present across all our projects utilizing the release mechanism.
2. The release is indeed created by when the plugin attempts to finalize it we receiving a 404 error
3. This behavior is completely random (i manually invoked the CLI, it occurred sporadically, sometimes happening with every call or just once in every three or four calls.) 

I hope this information will assist you in resolving the issue.

**Comment by lobsterkatie** [comment]
I'm adding some [logging](https://github.com/getsentry/sentry/pull/64595) to the cases in which the endpoint in question 404s. Hopefully this will give us at least some more information with which to debug this.

**Comment by slestang** [comment]
@lobsterkatie can you ping us (@KevinCalmant and myself) when this is in production so we can re-activate on 1 project the release creation and give you the time range when it is on.

**Comment by lobsterkatie** [comment]
@slestang @KevinCalmant - It lives!

For Sentaurs, in case it's of interest: The logs have been live since about 3 pm yesterday, and the vast majority (626/649) are from the release not being found rather than permissions being wrong. I spot-checked a few and indeed, the release seems missing, even ones which were tried almost a day ago. Will keep investigating...

**Comment by slestang** [comment]
@lobsterkatie I create several releases between 11:25 and 12:00 (GMT+1) without reproducing the issue :shrug: 

I will re-enable the Sentry plugin on one of our project tomorrow (today is release day) to make sure that over multiple builds and multiple branches it works fine. But the bug might have been fixed by another changes.

**Comment by lobsterkatie** [comment]
Great - glad it's working for you now! (Still not sure what the underlying issue is/was, though.)

Let me know how it goes tomorrow!

**Comment by slestang** [comment]
It seems to work all the time.
I think you can close this issue.
