### ISSUE TITLE
Bug in APIs to resolve Issues

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#66422]
### Steps to Reproduce

I received the following question from Linear:

We are marking Sentry issues as resolved when a linked Linear issue is closed. We do this using a PUT on the endpoint `https://sentry.io/api/0/issues/{issue_id}/` with
`{"status":"resolvedInNextRelease"}`.

2025-Oct-03: ☝🏻 this endpoint does not exist anymore.

As far as I know this used to correctly mark it as resolved in the NEXT release (similar to what you can do in the UI), but it appears to not work anymore. It just marks the issue as resolved in the current release. I also can't find anything about resolvedInNextRelease in your docs.

I took a look at what the Sentry UI does and it appears it sends a PUT to `https://us.sentry.io/api/0/projects/{organization_slug}/{project_slug}/issues/?id={issue_id}` with:
`{"status":"resolved","statusDetails":{"inNextRelease":true},"substatus":null}`.

<img width="304" height="241" alt="Image" src="https://github.com/user-attachments/assets/0874ab80-e428-4091-a64b-eadb53b679cd" />

<img width="502" height="115" alt="Image" src="https://github.com/user-attachments/assets/4d8caf07-d0a2-4858-9b80-1d008bf8a4ff" />

This works. If I hit the same endpoint with that data, it correctly shows up in the UI as marked as resolved in the next release.

But if I hit the endpoint we already use `https://sentry.io/api/0/issues/{issue_id}/` with
`{"status":"resolved","statusDetails":{"inNextRelease":true},"substatus":null}` it ignores `statusDetails` and just marks it as resolved in the current release.

From the documentation it appears that bulk editing issues would maybe support it, but not when updating a single issue:
[https://docs.sentry.io/api/events/bulk-mutate-a-list-of-issues/](https://docs.sentry.io/api/events/bulk-mutate-a-list-of-issues/)  vs [https://docs.sentry.io/api/events/update-an-issue/](https://docs.sentry.io/api/events/update-an-issue/)

As far as I can tell, that leaves me with two options:

* Calling the endpoint that your UI does (which isn't documented) or the bulk mutate endpoint (to update a single issue) to get this functionality. Neither seems logical and both would require the project_slug too, which we don't currently store, but we could of course start doing that.
* That you'll support statusDetails when updating a single issue. I don't see why it wouldn't be possible from a technical standpoint and having the API aligned seems right to me?

**Comment by scefali** [comment]
@Dhrumil-Sentry I am unable to replicate the bug. Both endpoints use the same underlying logic to update the groups ([this](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_group_index.py#L249-L255) and [this](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/group_details.py#L330-L332)). So they should behave the same in this regard.

**Comment by skbogner** [comment]
Hi. I don't know what I'm missing. Here's a video of me trying to use the two apis and the different results I get. I can't speak for what state the issue actually ends up in, but at least the values I get back differ:

https://github.com/getsentry/sentry/assets/2521488/25e51690-092f-4b24-8301-96f970e7dd88

**Comment by scefali** [comment]
@skbogner Ok, I see the problem now. For some reason, the two endpoints have different serializer logic. [One endpoint](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_group_index.py#L249-L255) uses the output of `update_groups` directly and the [other one](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/group_details.py#L347-L356) uses the serializer. For whatever reason, the two versions have diverged in implementation. But the actual _updating_ of data should be the same. You can verify this by making the GET request to the endpoint after each PUT request and comparing the content of those.

**Comment by skbogner** [comment]
They just don't behave similarly when I call them. I took two different unresolved issues that both returned the same beforehand:
```
	"status": "unresolved",
	"statusDetails": {},
```

One (1) I called `https://sentry.io/api/0/issues/<issue_id>/` with:
```
{"status":"resolved","statusDetails":{"inNextRelease":true},"substatus":null}
```

The other (2) I called `https://sentry.io/api/0/projects/linear/linear/issues/?id=<issue_id>` with:
```
{"status":"resolved","statusDetails":{"inNextRelease":true},"substatus":null}
```


Then calling GET on each to compare I get different results:
```
For (1):
	"status": "resolved",
	"statusDetails": {
		"inRelease": "1.22152.0",

For (2):
	"status": "resolved",
	"statusDetails": {
		"inNextRelease": true,
```


There seems to be an additional feature/bug of once an issue has been resolved to either of these statuses subsequent unresolve/resolves always ends up in the same result. So if I unresolve (2) and then resolve it with `https://sentry.io/api/0/issues/<issue_id>/` I end up with `"inNextRelease": true`. And if I unresolve (1) and call it with `https://sentry.io/api/0/projects/linear/linear/issues/?id=<issue_id>` I end up with `"inRelease": "1.22152.0"`.

**Comment by scefali** [comment]
@skbogner I guess this is a real bug, adding it to our backlog

**Comment by sandstrom** [comment]
@scefali Just checking in, any update on this one?

**Comment by sandstrom** [comment]
Thanks @Dhrumil-Sentry 😄

**Comment by roggenkemper** [comment]
@skbogner following up on this - i think there are 2 separate issues here that are happening.

1) With regards to your video, I think steve's initial guess was right in that the 2 serializers are behaving differently which is why the responses you get are different. 
2) The second problem I believe is related to how "in next release" works. You mentioned trying out the two requests on two different issues and seeing different results in the GET responses. I think what might be causing the difference is that fact that the two issues might have been "last seen" in different releases. For example, if one of the issues was last seen a while ago while the other was seen very recently (in the most recent release), we will get different results because the "next release" for the first issue was already a release that exists, while the "next release" doesn't exist yet for the second issue. 

We're working on fixing the first bug and adding a new feature that will allow you to "resolve in upcoming release" to solve the second problem stated

**Comment by sandstrom** [comment]
Just to chime in. 

If I have this list of releases (using dates for simplicity):

- 2024-01-22
- 2024-03-13
- 2024-04-24

And I have an issue that hasn't been seen since January, if today is end of April, why would it ever make sense to mark it as "in next release", and have that mean 2024-03-13?

Because if that usage isn't common (which I'd argue it isn't), then I wouldn't add a new mode, I'd change the behavior of the current mode (instead of adding a new one).

If you need to mark something as resolved in an already existing release, you'll know which one, and can just select it by name anyway.

**Comment by roggenkemper** [comment]
@sandstrom we're still relatively early on in the stages of trying to fix this use case, but we definitely appreciate the feedback. our main concern was breaking anyone's existing workflow if they do rely on the current implementation, but it is valid comment that it probably isn't super common

**Comment by sandstrom** [comment]
@roggenkemper Sounds good! Yeah, I think you'll save yourself some needless work by not introducing another mode.

**Comment by skbogner** [comment]
> 2\. The second problem I believe is related to how "in next release" works. You mentioned trying out the two requests on two different issues and seeing different results in the GET responses. I think what might be causing the difference is that fact that the two issues might have been "last seen" in different releases. For example, if one of the issues was last seen a while ago while the other was seen very recently (in the most recent release), we will get different results because the "next release" for the first issue was already a release that exists, while the "next release" doesn't exist yet for the second issue.

Seconding what @sandstrom said. I would never expect "next release" to mean "the one after the one where the issue was last seen". That also feels to me like something you'd never want. That said I understand the very valid concern to not break any existing workflows that might rely on this. Let us know what you end up with 👍

**Comment by snigdhas** [comment]
The team has been working on tweaks or fixes for the resolved/resolved in release logic. I don't think we'll be making a change to how resolved in next release works as part of this. To clarify, the ask here is then to reconcile the differences between the endpoints by supporting `statusDetails` when updating a single issue?

**Comment by meichstedt** [comment]
We are also facing this issue for quite some time, and it's very annoying. Several months ago, we switched to manually marking Linear issues as completed, but that totally screws cycle burndown charts, so we switched back just to see that Sentry issues still get resolved in the wrong version. The very annoying part here is, that the issues get re-opened as regressions even though they aren't.

I'm very disappointed to hear that the team has worked on this for 8 months, and seemingly nothing happened, and now it sounds like the issue is not getting fixed. Where do I need to send my feature acceleration cheque?

**Comment by Miras4207** [comment]
This is also issue for us and we never expected that `resolvedInNextVersion` would work this way. In our workflow, we push commits to fix issues and mark them as resolved in next version, hoping that they would be considered as regressed only if they happen again after new version is deployed. Instead, it’s often reopened as regression before the new version is released.

I understand that changing current behavior might be inconvenient. Therefore, would it be feasible to introduce something like `resolvedInFutureVersion` that would achieve this?

**Comment by armenzg** [comment]
Hello all,
The code here has changed quite a bit.

We have done a lot of clean-up of the code base in the last 3 months and I remember my team making changes to the behavior of resolving issues.

Could you please file new tickets if you're still encountering this or similar?
