### ISSUE TITLE
Team admins are unable to link teams to slack channel.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#90807]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install the Slack integration
2. In Sentry, add a user with "Member" role to a team as "Team admin"
3. In Slack, link the Slack identity to the user using `/sentry link`
4. In Slack try to link a team to a channel using `/sentry link team`

### Expected Result

Link the team the user is "team admin" to a Slack channel.

### Actual Result

Get the following response from Sentry app:
> You must be a Sentry organisation admin/manager/owner or a team admin to link or unlink teams.

According to this, a user with team admin permissions can link a Slack channel to the team he is an admin of. 

This was also reported by a user in this [internal ticket.](https://sentry.zendesk.com/agent/tickets/151118). The workaround is to have a user with Manager, Admin or Owner permission to link the channel.

### Product Area

Settings - Integrations

### Link

Affected user: https://dev-curumas.sentry.io/settings/members/13966591/

**Comment by sentaur-athena** [comment]
Added to triage. Will post an update in the next 2 weeks.

**Comment by cathteng** [comment]
I cannot reproduce this issue. Can you please provide the steps to reproduce @rodolfoBee ?

**Comment by rodolfoBee** [comment]
@cathteng did the steps provided in the description did not work? He is a member of 4 organisations.

Here is the user from my organisation:
https://dev-curumas.sentry.io/settings/members/13966591/

And the screenshot from Slack:

<img width="751" alt="Image" src="https://github.com/user-attachments/assets/fc9c3711-d566-49e3-85da-5d3d2cb1023c" />

**Comment by cathteng** [comment]
Our current design has made it difficult for us to select the correct organization and region when the user has multiple organizations in different regions. The issue here is a symptom of this larger design problem.

It will require a non-trivial amount of work to account for this as a whole, but we are aware of this. We'll keep tracking this issue as we tackle the larger problem.

**Comment by iamrajjoshi** [comment]
ECO-696

**Comment by rodolfoBee** [comment]
Reopening this issue as my user is still affected by this issue.

**Comment by leeandher** [comment]
Didn't intend to close this, probably synced with linear -- there's a fix/feature in but were incrementally releasing it since the code path affects all slack installs. 

Ill update here when it's GA.

**Comment by leeandher** [comment]
The fix has been fully released in SaaS and should be available to all customers. We've made a change to the slash command, so if you're encountering this, please try `/sentry link team [organization_slug]` as it appears in the new `/sentry help` command. 

The organization slug can be found in `Settings > Organization Settings > Organization Slug` or in the URL, `[organization-slug].sentry.io`.

For example, `/sentry link team acme`. The URLs we issue are region specific, so this should resolve the cross-region issue!

Please reopen if anyone is still experiencing this!

**Comment by rodolfoBee** [comment]
Still seeing the problem:

<img width="633" height="341" alt="Image" src="https://github.com/user-attachments/assets/4dba3a02-4a0a-4b6c-b7fa-1d532bab32ee" />

https://github.com/user-attachments/assets/b26229e5-510f-48e8-b65d-01ed81ef6573

**Comment by rodolfoBee** [comment]
@leeandher can you provide an update on my comment before closing the ticket?

**Comment by leeandher** [comment]
> @leeandher can you provide an update on my comment before closing the ticket? 

Sorry it keeps happening 🥲 I just thought I forgot to move the linear ticket into completed, I will take a look at the permissions issue.

**Comment by rodolfoBee** [comment]
i tried again just now and it is working, thank you for the fix and sorry for the annoyance

**Comment by leeandher** [comment]
> i tried again just now and it is working, thank you for the fix and sorry for the annoyance

@rodolfoBee  I think I closed this ticket prior to rolling out to 100%, so it was rightly broken. Thank you for reopening and I'll be more mindful moving tickets around in Linear when they're linked in GitHub! Happy to see it's fixed 👏
